name: CI pipeline
on: [push]
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: "5.0.x"
#       - run: dotnet build ./SimpleWebHalloWorld.csproj
  jobs:
    build-and-push-api:
      runs-on: ubuntu-latest
      # env: 
      #   working-directory: .
      steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }};
          password: ${{ secrets.PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/jonaslindell-th/HelloWorld:latest
            ghcr.io/jonaslindell-th/HelloWorld:${{ github.run_number }}