name: CI pipeline
on: [push]
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }};
          password: ${{ secrets.PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/jonaslindell-th/helloworld:latest
            ghcr.io/jonaslindell-th/helloworld:${{ github.run_number }}
